<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Rel attribute' => 'Atrybut rel',
    'Meta description' => '@@Meta opis@@',
    'Meta keywords' => '@@Meta słowa kluczowe@@',
    'Meta title' => '@@Meta tytuł strony@@',
    'Attribute {attribute} is not defined' => 'Atrybut {attribute} nie jest zdefiniowany',
    'Bottom javascript' => 'Dolny javascript',
    'Bottom menu' => 'Dolne menu',
    'Bottom submenu' => 'Dolne podmenu',
    'Copyright' => 'Copyright',
    'Default meta description' => 'Domyślny opis',
    'Default meta keywords' => 'Domyślne słowa kluczowe',
    'Default meta title' => 'Domyślny tytuł',
    'Favicon' => 'Favicon',
    'Footer' => 'Stopka',
    'Format: <code>http://exmple.com/url-to-page</code> or <code>/url-to-page</code>' => 'Format: <code>http://exmple.com/link-do-strony</code> lub <code>/link-do-strony</code>',
    'General' => 'Główne',
    'Grid' => 'Siatka',
    'Home page' => 'Strona główna',
    'ID' => 'ID',
    'Image' => 'Obraz',
    'Image mobile' => 'Obraz mobile',
    'Javascript' => 'Javascript',
    'Language' => 'Język',
    'Languages' => 'Języki',
    'Link' => 'Link',
    'Link title' => 'Tytuł linku',
    'Menu' => 'Menu',
    'Menu ID' => 'ID Menu',
    'Meta' => 'Meta',
    'Meta tags' => 'Meta tagi',
    'New tab' => 'Nowa zakładka',
    'No' => 'Nie',
    'Page' => 'Strona',
    'Page ID' => 'ID strony',
    'Page Item ID' => 'ID elementu strony',
    'Pages' => 'Strony',
    'Parent ID' => 'ID rodzica',
    'Publish' => 'Publikuj',
    'Sections' => 'Sekcje',
    'Settings' => 'Ustawienia',
    'Slider' => 'Slider',
    'Sort' => 'Kolejność',
    'Submenu' => 'Podmenu',
    'Template' => 'Szablon',
    'Text' => 'Tekst',
    'Text page' => 'Strona tekstowa',
    'Text pages' => 'Strony tekstowe',
    'Title' => 'Tytuł',
    'Top javascript' => 'Górny javascript',
    'Top menu' => 'Górne menu',
    'Top submenu' => 'Górne podmenu',
    'Type' => 'Typ',
    'Url' => 'Url',
    'Without &lt;script&gt; tag' => 'Bez tagu &lt;script&gt;',
    'Yes' => 'Tak',
    'choose' => 'wybierz',
];
