<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Attribute {attribute} is not defined' => 'Atrybut {attribute} nie jest zdefiniowany',
    'Bottom menu' => 'Dolne menu',
    'Bottom submenu' => 'Dolne podmenu',
    'Format: <code>http://exmple.com/url-to-page</code> or <code>/url-to-page</code>' => 'Format: <code>http://exmple.com/link-do-strony</code> lub <code>/link-do-strony</code>',
    'General' => 'Główne',
    'Home page' => 'Strona główna',
    'Home slider' => 'Slider strona główna',
    'ID' => 'ID',
    'Image' => 'Obraz',
    'Language' => 'Język',
    'Languages' => 'Języki',
    'Link' => 'Link',
    'Menu' => 'Menu',
    'Menu ID' => 'ID Menu',
    'Meta description' => 'Meta opis',
    'Meta keywords' => 'Meta słowa kluczowe',
    'Meta tags' => 'Meta tagi',
    'Meta title' => 'Meta tytuł strony',
    'New tab' => 'Nowa zakładka',
    'No' => 'Nie',
    'Page' => 'Strona',
    'Page ID' => 'ID strony',
    'Page Item ID' => 'ID elementu strony',
    'Pages' => 'Strony',
    'Parent ID' => 'ID rodzica',
    'Publish' => 'Publikuj',
    'Settings' => 'Ustawienia',
    'Slider' => 'Slider',
    'Sort' => 'Kolejność',
    'Submenu' => 'Podmenu',
    'Template' => 'Szablon',
    'Text' => 'Tekst',
    'Text page' => 'Strona tekstowa',
    'Text pages' => 'Strony tekstowe',
    'Title' => 'Tytuł',
    'Top menu' => 'Górne menu',
    'Top submenu' => 'Górne podmenu',
    'Type' => 'Typ',
    'Url' => 'Url',
    'Yes' => 'Tak',
    'choose' => 'wybierz',
];
